apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
spec:
  type: NodePort
  selector:
    app: tictactoe
  ports:
    # We want to map port 8080 of the container to pod 8080 of the pod then map port 8080 of the pod to port 30080 of the Node
    - port: 8080
      targetPort: 8080
      nodePort: 30080
